//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://calc/", ConfigurationName="WebServiceAluguelVeiculo.InterfaceServ")]
    public interface InterfaceServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/solicitacaoFormLocacaoRequest", ReplyAction="http://calc/InterfaceServ/solicitacaoFormLocacaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool solicitacaoFormLocacao(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/solicitacaoFormLocacaoRequest", ReplyAction="http://calc/InterfaceServ/solicitacaoFormLocacaoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> solicitacaoFormLocacaoAsync(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/novoClienteConectadoRequest", ReplyAction="http://calc/InterfaceServ/novoClienteConectadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void novoClienteConectado(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/novoClienteConectadoRequest", ReplyAction="http://calc/InterfaceServ/novoClienteConectadoResponse")]
        System.Threading.Tasks.Task novoClienteConectadoAsync(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/consultarVeiculosRequest", ReplyAction="http://calc/InterfaceServ/consultarVeiculosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractCollection))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.arrayList consultarVeiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/consultarVeiculosRequest", ReplyAction="http://calc/InterfaceServ/consultarVeiculosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.arrayList> consultarVeiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/devolverVeiculoRequest", ReplyAction="http://calc/InterfaceServ/devolverVeiculoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractCollection))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool devolverVeiculo(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/devolverVeiculoRequest", ReplyAction="http://calc/InterfaceServ/devolverVeiculoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> devolverVeiculoAsync(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/alugarVeicRequest", ReplyAction="http://calc/InterfaceServ/alugarVeicResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractCollection))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool alugarVeic(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, int arg8, string arg9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/alugarVeicRequest", ReplyAction="http://calc/InterfaceServ/alugarVeicResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> alugarVeicAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, int arg8, string arg9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/regInteresseVeicRequest", ReplyAction="http://calc/InterfaceServ/regInteresseVeicResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractCollection))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool regInteresseVeic(string arg0, float arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calc/InterfaceServ/regInteresseVeicRequest", ReplyAction="http://calc/InterfaceServ/regInteresseVeicResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> regInteresseVeicAsync(string arg0, float arg1);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://calc/")]
    public partial class arrayList : abstractList {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(arrayList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://calc/")]
    public abstract partial class abstractList : abstractCollection {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(arrayList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://calc/")]
    public abstract partial class abstractCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceServChannel : AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.InterfaceServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceServClient : System.ServiceModel.ClientBase<AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.InterfaceServ>, AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.InterfaceServ {
        
        public InterfaceServClient() {
        }
        
        public InterfaceServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool solicitacaoFormLocacao(string arg0) {
            return base.Channel.solicitacaoFormLocacao(arg0);
        }
        
        public System.Threading.Tasks.Task<bool> solicitacaoFormLocacaoAsync(string arg0) {
            return base.Channel.solicitacaoFormLocacaoAsync(arg0);
        }
        
        public void novoClienteConectado(string arg0) {
            base.Channel.novoClienteConectado(arg0);
        }
        
        public System.Threading.Tasks.Task novoClienteConectadoAsync(string arg0) {
            return base.Channel.novoClienteConectadoAsync(arg0);
        }
        
        public AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.arrayList consultarVeiculos() {
            return base.Channel.consultarVeiculos();
        }
        
        public System.Threading.Tasks.Task<AluguelVeiculosUTF_Cliente.WebServiceAluguelVeiculo.arrayList> consultarVeiculosAsync() {
            return base.Channel.consultarVeiculosAsync();
        }
        
        public bool devolverVeiculo(string arg0) {
            return base.Channel.devolverVeiculo(arg0);
        }
        
        public System.Threading.Tasks.Task<bool> devolverVeiculoAsync(string arg0) {
            return base.Channel.devolverVeiculoAsync(arg0);
        }
        
        public bool alugarVeic(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, int arg8, string arg9) {
            return base.Channel.alugarVeic(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
        }
        
        public System.Threading.Tasks.Task<bool> alugarVeicAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, int arg8, string arg9) {
            return base.Channel.alugarVeicAsync(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
        }
        
        public bool regInteresseVeic(string arg0, float arg1) {
            return base.Channel.regInteresseVeic(arg0, arg1);
        }
        
        public System.Threading.Tasks.Task<bool> regInteresseVeicAsync(string arg0, float arg1) {
            return base.Channel.regInteresseVeicAsync(arg0, arg1);
        }
    }
}
